application:
  # configuring external calls
  star-wars-api:
    url: https://swapi.dev/api

spring:
  datasource:
    # database in-memory for tests
    url: jdbc:h2:mem:testdb

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update