spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./src/main/resources/h2data/database
    driverClassName: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true # If using H2 Database, enable
      path: /h2 # customize H2 database console path

server:
  port: 8989

  # show error message when throwing error
  error:
    include-message: always
    include-binding-errors: always